version: "3.4"
services:
  cassandra:
    image: cassandra
    ports:
      - "9042"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: build

    command: "wait-for-it --timeout=30 cassandra:9042 -- make test-ci"
    ports:
      - "3000"
    environment:
      LOG_LEVEL: debug
      CASSANDRA_HOSTS: "cassandra:9042"
    depends_on:
      - cassandra
